version: "3.7"

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    networks:
      - nginx

  ngrok:
    container_name: ngrok
    image: wernight/ngrok:latest
    command: ngrok http nginx:80
    networks:
      - nginx
    ports:
      -  '4040:4040'

networks:
  nginx: 